// <auto-generated />
using System;
using FuelEase.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelEase.EntityFramework.Migrations
{
    [DbContext(typeof(FuelEaseDbContext))]
    [Migration("20240811165043_AddPKElectronicsSettungs")]
    partial class AddPKElectronicsSettungs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuelEase.Domain.Models.CashRegister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CashRegisterType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CashRegisters");

                    b.HasDiscriminator<int>("CashRegisterType").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Controller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaudRate")
                        .HasColumnType("int");

                    b.Property<int>("ControllerType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Controllers");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.EventPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("EventsPanel");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("SalesTax")
                        .HasColumnType("float");

                    b.Property<string>("TNVED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitOfMeasurementId")
                        .HasColumnType("int");

                    b.Property<bool>("ValueAddedTax")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasurementId");

                    b.ToTable("Fuels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deleted = false,
                            Name = "АИ-92",
                            Price = 0m,
                            SalesTax = 0.0,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        },
                        new
                        {
                            Id = 2,
                            Deleted = false,
                            Name = "АИ-95",
                            Price = 0m,
                            SalesTax = 0.0,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        },
                        new
                        {
                            Id = 3,
                            Deleted = false,
                            Name = "АИ-98",
                            Price = 0m,
                            SalesTax = 0.0,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        },
                        new
                        {
                            Id = 4,
                            Deleted = false,
                            Name = "АИ-100",
                            Price = 0m,
                            SalesTax = 0.0,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        },
                        new
                        {
                            Id = 5,
                            Deleted = false,
                            Name = "ДТ",
                            Price = 0m,
                            SalesTax = 0.0,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        });
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelIntake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("FuelIntakes");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelNozzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nozzle")
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<int>("Tube")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ControllerId");

                    b.HasIndex("TankId");

                    b.ToTable("FuelNozzles");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelNozzleCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Beginning")
                        .HasColumnType("float");

                    b.Property<double>("Ending")
                        .HasColumnType("float");

                    b.Property<int>("FuelNozzleId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuelNozzleId");

                    b.HasIndex("ShiftId");

                    b.ToTable("FuelNozzleCounters");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelRevaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.ToTable("FuelRevaluations");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FiscalDocument")
                        .HasColumnType("int");

                    b.Property<int?>("FiscalModule")
                        .HasColumnType("int");

                    b.Property<int?>("FuelNozzleId")
                        .HasColumnType("int");

                    b.Property<int>("FuelSaleStatus")
                        .HasColumnType("int");

                    b.Property<int>("NozzleId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<double>("ReceivedQuantity")
                        .HasColumnType("float");

                    b.Property<decimal>("ReceivedSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RegistrationNumber")
                        .HasColumnType("int");

                    b.Property<string>("ReturnCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuelNozzleId");

                    b.HasIndex("NozzleId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TankId");

                    b.ToTable("FuelSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelTransferColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaudRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FuelTransferColumns");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Nozzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address")
                        .HasColumnType("int");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<bool>("BlockingChannelOperation")
                        .HasColumnType("bit");

                    b.Property<int>("ConstantFlowReduction")
                        .HasColumnType("int");

                    b.Property<int>("FuelTransferColumnId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NozzleAddress")
                        .HasColumnType("int");

                    b.Property<int>("NozzleSensor")
                        .HasColumnType("int");

                    b.Property<int>("OverflowConstant")
                        .HasColumnType("int");

                    b.Property<int>("PumpAccelerationTime")
                        .HasColumnType("int");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("SurveyMethod")
                        .HasColumnType("int");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<int>("Tube")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuelTransferColumnId");

                    b.HasIndex("TankId");

                    b.ToTable("Nozzles");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<double>("MinimumSize")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "литр"
                        },
                        new
                        {
                            Id = 2,
                            Name = "метр куб."
                        },
                        new
                        {
                            Id = 3,
                            Name = "кВт*ч"
                        });
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UnregisteredSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FuelNozzleId")
                        .HasColumnType("int");

                    b.Property<bool>("KeyboardMode")
                        .HasColumnType("bit");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuelNozzleId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TankId");

                    b.ToTable("UnregisteredSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 11, 22, 50, 43, 266, DateTimeKind.Local).AddTicks(6055),
                            Deleted = false,
                            FullName = "Администратор",
                            IsAdmin = false,
                            Password = "1",
                            UserRoleId = 1
                        });
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кассир"
                        });
                });

            modelBuilder.Entity("FuelEase.Domain.Views.NozzleMeterValueView", b =>
                {
                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.ToTable((string)null);

                    b.ToView("NozzleMeterValueView", (string)null);
                });

            modelBuilder.Entity("FuelEase.Domain.Views.TankFuelQuantityView", b =>
                {
                    b.Property<double>("CurrentFuelQuantity")
                        .HasColumnType("float");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<double>("MinimumSize")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.ToTable((string)null);

                    b.ToView("TankFuelQuantityView", (string)null);
                });

            modelBuilder.Entity("FuelEase.Domain.Models.EKassaCashRegister", b =>
                {
                    b.HasBaseType("FuelEase.Domain.Models.CashRegister");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FuelEase.Domain.Models.MFCashRegister", b =>
                {
                    b.HasBaseType("FuelEase.Domain.Models.CashRegister");

                    b.Property<string>("MFName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FuelEase.Domain.Models.EventPanel", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("EventsPanel")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Fuel", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Fuels")
                        .HasForeignKey("UnitOfMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelIntake", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("FuelIntakes")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelNozzle", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Controller", "Controller")
                        .WithMany("FuelNozzles")
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("FuelNozzles")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Controller");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelNozzleCounter", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.FuelNozzle", "FuelNozzle")
                        .WithMany("FuelNozzleCounter")
                        .HasForeignKey("FuelNozzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("FuelNozzleCounters")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelNozzle");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelRevaluation", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Fuel", "Fuel")
                        .WithMany("FuelRevaluations")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelSale", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.FuelNozzle", null)
                        .WithMany("FuelSales")
                        .HasForeignKey("FuelNozzleId");

                    b.HasOne("FuelEase.Domain.Models.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("FuelSales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("FuelSales")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Nozzle");

                    b.Navigation("Shift");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Nozzle", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.FuelTransferColumn", "FuelTransferColumn")
                        .WithMany("Nozzles")
                        .HasForeignKey("FuelTransferColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("Nozzle")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelTransferColumn");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Shift", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Tank", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Fuel", "Fuel")
                        .WithMany("Tanks")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UnregisteredSale", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.FuelNozzle", "FuelNozzle")
                        .WithMany("UnregisteredSales")
                        .HasForeignKey("FuelNozzleId");

                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("UnregisteredSales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("UnregisteredSales")
                        .HasForeignKey("TankId");

                    b.Navigation("FuelNozzle");

                    b.Navigation("Shift");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.User", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Controller", b =>
                {
                    b.Navigation("FuelNozzles");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Fuel", b =>
                {
                    b.Navigation("FuelRevaluations");

                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelNozzle", b =>
                {
                    b.Navigation("FuelNozzleCounter");

                    b.Navigation("FuelSales");

                    b.Navigation("UnregisteredSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelTransferColumn", b =>
                {
                    b.Navigation("Nozzles");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Shift", b =>
                {
                    b.Navigation("EventsPanel");

                    b.Navigation("FuelNozzleCounters");

                    b.Navigation("FuelSales");

                    b.Navigation("UnregisteredSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Tank", b =>
                {
                    b.Navigation("FuelIntakes");

                    b.Navigation("FuelNozzles");

                    b.Navigation("FuelSales");

                    b.Navigation("Nozzle");

                    b.Navigation("UnregisteredSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Fuels");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.User", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
