// <auto-generated />
using System;
using FuelEase.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelEase.EntityFramework.Migrations
{
    [DbContext(typeof(FuelEaseDbContext))]
    [Migration("20250408140113_DoubleToDecimal")]
    partial class DoubleToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuelEase.Domain.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.DiscountSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FuelSaleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("FuelSaleId")
                        .IsUnique();

                    b.ToTable("DiscountSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Discounts.DiscountFuel", b =>
                {
                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.HasKey("DiscountId", "FuelId");

                    b.HasIndex("FuelId");

                    b.ToTable("DiscountFuels");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Discounts.DiscountTariffPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaximumValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("DiscountTariffPlans");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.EventPanel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("EventEntity")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("EventsPanel");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FiscalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Check")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FiscalDocument")
                        .HasColumnType("int");

                    b.Property<string>("FiscalModule")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnCheck")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FiscalDatas");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Fuel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalesTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TNVED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitOfMeasurementId")
                        .HasColumnType("int");

                    b.Property<bool>("ValueAddedTax")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("UnitOfMeasurementId");

                    b.ToTable("Fuels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#F6B511",
                            Deleted = false,
                            Name = "АИ-92",
                            Price = 0m,
                            SalesTax = 0m,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#ED2D38",
                            Deleted = false,
                            Name = "АИ-95",
                            Price = 0m,
                            SalesTax = 0m,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#4FA800",
                            Deleted = false,
                            Name = "АИ-98",
                            Price = 0m,
                            SalesTax = 0m,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#FFD700",
                            Deleted = false,
                            Name = "АИ-100",
                            Price = 0m,
                            SalesTax = 0m,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#737373",
                            Deleted = false,
                            Name = "ДТ",
                            Price = 0m,
                            SalesTax = 0m,
                            UnitOfMeasurementId = 1,
                            ValueAddedTax = false
                        });
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelIntake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TankId");

                    b.ToTable("FuelIntakes");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelRevaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<decimal>("NewPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.ToTable("FuelRevaluations");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ChangeSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CustomerSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiscountSaleId")
                        .HasColumnType("int");

                    b.Property<int?>("FiscalDataId")
                        .HasColumnType("int");

                    b.Property<int>("FuelSaleStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsForSum")
                        .HasColumnType("bit");

                    b.Property<int>("NozzleId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReceivedCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReceivedSum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FiscalDataId")
                        .IsUnique()
                        .HasFilter("[FiscalDataId] IS NOT NULL");

                    b.HasIndex("NozzleId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TankId");

                    b.ToTable("FuelSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Nozzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.Property<int>("Tube")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("Nozzles");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.NozzleShiftCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BeginCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EndCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NozzleId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NozzleId");

                    b.HasIndex("ShiftId");

                    b.ToTable("NozzleShiftCounters");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.TankShiftCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BeginCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EndCount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("TankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TankId");

                    b.ToTable("TankShiftCounters");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UnitOfMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "литр"
                        },
                        new
                        {
                            Id = 2,
                            Name = "метр куб."
                        },
                        new
                        {
                            Id = 3,
                            Name = "кВт*ч"
                        });
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UnregisteredSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NozzleId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NozzleId");

                    b.HasIndex("ShiftId");

                    b.ToTable("UnregisteredSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 4, 8, 20, 1, 12, 915, DateTimeKind.Local).AddTicks(5210),
                            Deleted = false,
                            FullName = "Администратор",
                            IsAdmin = false,
                            Password = "1",
                            UserRoleId = 1
                        });
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Администратор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Кассир"
                        });
                });

            modelBuilder.Entity("FuelEase.Domain.Views.NozzleMeterValueView", b =>
                {
                    b.Property<int>("ControllerId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.ToTable((string)null);

                    b.ToView("NozzleMeterValueView", (string)null);
                });

            modelBuilder.Entity("FuelEase.Domain.Views.TankFuelQuantityView", b =>
                {
                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentFuelQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FuelId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("MinimumSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("TankFuelQuantityView", (string)null);
                });

            modelBuilder.Entity("FuelEase.Domain.Models.DiscountSale", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Discount", "Discount")
                        .WithMany("DiscountSales")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.FuelSale", "FuelSale")
                        .WithOne("DiscountSale")
                        .HasForeignKey("FuelEase.Domain.Models.DiscountSale", "FuelSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("FuelSale");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Discounts.DiscountFuel", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Discount", "Discount")
                        .WithMany("DiscountFuels")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Fuel", "Fuel")
                        .WithMany("DiscountFuels")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Fuel");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Discounts.DiscountTariffPlan", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Discount", "Discount")
                        .WithMany("DiscountTariffPlans")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.EventPanel", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("EventsPanel")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Fuel", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.UnitOfMeasurement", "UnitOfMeasurement")
                        .WithMany("Fuels")
                        .HasForeignKey("UnitOfMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitOfMeasurement");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelIntake", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("FuelIntakes")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("FuelIntakes")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelRevaluation", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Fuel", "Fuel")
                        .WithMany("FuelRevaluations")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelSale", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.FiscalData", "FiscalData")
                        .WithOne("FuelSale")
                        .HasForeignKey("FuelEase.Domain.Models.FuelSale", "FiscalDataId");

                    b.HasOne("FuelEase.Domain.Models.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("FuelSales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("FuelSales")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FiscalData");

                    b.Navigation("Nozzle");

                    b.Navigation("Shift");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Nozzle", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("Nozzle")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.NozzleShiftCounter", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Nozzle", "Nozzle")
                        .WithMany("NozzleShiftCounters")
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("NozzleShiftCounters")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nozzle");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Shift", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.User", "User")
                        .WithMany("Shifts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Tank", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Fuel", "Fuel")
                        .WithMany("Tanks")
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.TankShiftCounter", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("TankShiftCounters")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Tank", "Tank")
                        .WithMany("TankShiftCounters")
                        .HasForeignKey("TankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UnregisteredSale", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.Nozzle", "Nozzle")
                        .WithMany()
                        .HasForeignKey("NozzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelEase.Domain.Models.Shift", "Shift")
                        .WithMany("UnregisteredSales")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nozzle");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.User", b =>
                {
                    b.HasOne("FuelEase.Domain.Models.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Discount", b =>
                {
                    b.Navigation("DiscountFuels");

                    b.Navigation("DiscountSales");

                    b.Navigation("DiscountTariffPlans");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FiscalData", b =>
                {
                    b.Navigation("FuelSale")
                        .IsRequired();
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Fuel", b =>
                {
                    b.Navigation("DiscountFuels");

                    b.Navigation("FuelRevaluations");

                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.FuelSale", b =>
                {
                    b.Navigation("DiscountSale");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Nozzle", b =>
                {
                    b.Navigation("NozzleShiftCounters");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Shift", b =>
                {
                    b.Navigation("EventsPanel");

                    b.Navigation("FuelIntakes");

                    b.Navigation("FuelSales");

                    b.Navigation("NozzleShiftCounters");

                    b.Navigation("TankShiftCounters");

                    b.Navigation("UnregisteredSales");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.Tank", b =>
                {
                    b.Navigation("FuelIntakes");

                    b.Navigation("FuelSales");

                    b.Navigation("Nozzle");

                    b.Navigation("TankShiftCounters");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UnitOfMeasurement", b =>
                {
                    b.Navigation("Fuels");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.User", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("FuelEase.Domain.Models.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
