//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIT.GasStation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class HotKeys : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotKeys defaultInstance = ((HotKeys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotKeys())));
        
        public static HotKeys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public string FuelSaleCashless {
            get {
                return ((string)(this["FuelSaleCashless"]));
            }
            set {
                this["FuelSaleCashless"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public string FuelSaleCash {
            get {
                return ((string)(this["FuelSaleCash"]));
            }
            set {
                this["FuelSaleCash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F7")]
        public string FuelSaleTicket {
            get {
                return ((string)(this["FuelSaleTicket"]));
            }
            set {
                this["FuelSaleTicket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enter")]
        public string FuelSale {
            get {
                return ((string)(this["FuelSale"]));
            }
            set {
                this["FuelSale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/")]
        public string StartFullFueling {
            get {
                return ((string)(this["StartFullFueling"]));
            }
            set {
                this["StartFullFueling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F4")]
        public string FuelSaleStatement {
            get {
                return ((string)(this["FuelSaleStatement"]));
            }
            set {
                this["FuelSaleStatement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F2")]
        public string FuelSaleDiscountCard {
            get {
                return ((string)(this["FuelSaleDiscountCard"]));
            }
            set {
                this["FuelSaleDiscountCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F3")]
        public string FuelSaleCard {
            get {
                return ((string)(this["FuelSaleCard"]));
            }
            set {
                this["FuelSaleCard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F9")]
        public string FuelSaleOther {
            get {
                return ((string)(this["FuelSaleOther"]));
            }
            set {
                this["FuelSaleOther"] = value;
            }
        }
    }
}
