//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KIT.GasStation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class HotKeys : global::System.Configuration.ApplicationSettingsBase {
        
        private static HotKeys defaultInstance = ((HotKeys)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HotKeys())));
        
        public static HotKeys Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public string FuelSaleCashless {
            get {
                return ((string)(this["FuelSaleCashless"]));
            }
            set {
                this["FuelSaleCashless"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F1")]
        public string FuelSaleCash {
            get {
                return ((string)(this["FuelSaleCash"]));
            }
            set {
                this["FuelSaleCash"] = value;
            }
        }
    }
}
